# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate image

Name:           rust-%{crate}
Version:        0.22.4
Release:        2%{?dist}
Summary:        Imaging library written in Rust

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/image
Source:         %{crates_source}
# Initial patched metadata
# * Bump to tiff 0.4, https://github.com/image-rs/image/pull/1081
Patch0:         image-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Imaging library written in Rust. Provides basic filters and decoders for the
most common image formats.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md CHANGES.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+benchmarks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+benchmarks-devel %{_description}

This package contains library source intended for building other packages
which use "benchmarks" feature of "%{crate}" crate.

%files       -n %{name}+benchmarks-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+bmp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bmp-devel %{_description}

This package contains library source intended for building other packages
which use "bmp" feature of "%{crate}" crate.

%files       -n %{name}+bmp-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dxt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dxt-devel %{_description}

This package contains library source intended for building other packages
which use "dxt" feature of "%{crate}" crate.

%files       -n %{name}+dxt-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+gif-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gif-devel %{_description}

This package contains library source intended for building other packages
which use "gif" feature of "%{crate}" crate.

%files       -n %{name}+gif-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+gif_codec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gif_codec-devel %{_description}

This package contains library source intended for building other packages
which use "gif_codec" feature of "%{crate}" crate.

%files       -n %{name}+gif_codec-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hdr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hdr-devel %{_description}

This package contains library source intended for building other packages
which use "hdr" feature of "%{crate}" crate.

%files       -n %{name}+hdr-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+ico-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ico-devel %{_description}

This package contains library source intended for building other packages
which use "ico" feature of "%{crate}" crate.

%files       -n %{name}+ico-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+jpeg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jpeg-devel %{_description}

This package contains library source intended for building other packages
which use "jpeg" feature of "%{crate}" crate.

%files       -n %{name}+jpeg-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+jpeg-decoder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jpeg-decoder-devel %{_description}

This package contains library source intended for building other packages
which use "jpeg-decoder" feature of "%{crate}" crate.

%files       -n %{name}+jpeg-decoder-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+jpeg_rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jpeg_rayon-devel %{_description}

This package contains library source intended for building other packages
which use "jpeg_rayon" feature of "%{crate}" crate.

%files       -n %{name}+jpeg_rayon-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+png-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+png-devel %{_description}

This package contains library source intended for building other packages
which use "png" feature of "%{crate}" crate.

%files       -n %{name}+png-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+png_codec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+png_codec-devel %{_description}

This package contains library source intended for building other packages
which use "png_codec" feature of "%{crate}" crate.

%files       -n %{name}+png_codec-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pnm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pnm-devel %{_description}

This package contains library source intended for building other packages
which use "pnm" feature of "%{crate}" crate.

%files       -n %{name}+pnm-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+scoped_threadpool-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+scoped_threadpool-devel %{_description}

This package contains library source intended for building other packages
which use "scoped_threadpool" feature of "%{crate}" crate.

%files       -n %{name}+scoped_threadpool-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tga-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tga-devel %{_description}

This package contains library source intended for building other packages
which use "tga" feature of "%{crate}" crate.

%files       -n %{name}+tga-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tiff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tiff-devel %{_description}

This package contains library source intended for building other packages
which use "tiff" feature of "%{crate}" crate.

%files       -n %{name}+tiff-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+webp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webp-devel %{_description}

This package contains library source intended for building other packages
which use "webp" feature of "%{crate}" crate.

%files       -n %{name}+webp-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# Missing test file
%cargo_test -- -- --skip dynimage::test::image_dimensions --skip png::tests::ensure_no_decoder_off_by_one
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.22.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jan 16 2020 Josh Stone <jistone@redhat.com> - 0.22.4-1
- Update to 0.22.4

* Tue Nov 19 2019 Josh Stone <jistone@redhat.com> - 0.22.3-1
- Update to 0.22.3

* Sun Sep 08 16:53:42 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.22.2-1
- Update to 0.22.2

* Sun Sep 01 20:48:08 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.22.1-1
- Update to 0.22.1

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.21.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jun 22 20:49:22 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.21.2-2
- Regenerate

* Sun Jun 09 17:07:34 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.21.2-1
- Update to 0.21.2

* Mon Apr 15 2019 Josh Stone <jistone@redhat.com> - 0.21.1-1
- Update to 0.21.1

* Fri Mar 15 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.21.0-1
- Initial package
